### PR TITLE
Responsive UI

### PR DESCRIPTION
**Pull request by voknelis**
Hi atravkovs,

I've made a bit of improvements regarding responsivity for small screens
Please, consider this PR to be checked

### CODE REVIEW

**Review by atravkovs — CHANGES_REQUESTED** [review]
Hi, @voknelis !

First of all, Thank you for making improvements in UI! Especially liked "selected balance" addition.

However, while it looks much better on smaller screens, it uses horizontal space less efficiently.
For example, before it was possible to view 5 teams in a row on 1920x1080 resolution, while now it is only 4. Also, I believe "Lobby" section gets unnecessarily large on wider screens, it not only uses "Teams" section space, but also less compact format requires more eye movement (bearable on FullHD, but definitely overkill on wider screens).

It is important, as i.e. when comparing individual teams, it is beneficial to fit as many teams on screen as possible (to compare them without the need for scrolling).

Can you suggest any changes to improve that? Otherwise, I will be ready to merge&publish that as we will decide on that part.

And thanks again for suggested changes, much appreciated!

**Comment by voknelis** [comment]
Good evening @atravkovs,

Thanks for quick response and your feedback!
I apologize for this careless breakpoints checking. By default I use 125% resolution scaling, so it looked good on my screen.

I suggest the following improvements:
- reduce max card width from `270px` to `250px`, so it can fit 5 teams at 1920x1080 resolution
- add following widescreen breakpoints to Teams and Lobby sections `col-xl-3` and `col-xl-9` accordingly

These changes allow us to use section space more efficiently and effectively.

Should I commit the changes and create another pr?

**Comment by atravkovs** [comment]
@voknelis I would suggest leaving "Lobby" section fixed on larger screens (there is no need to scale it on larger screens), then max card width would remain around 270px (for 1920x1080). Otherwise, I guess you can just publish your changes to this branch, and I will be able to merge everything in the current PR. Thanks!

**Review by atravkovs — APPROVED** [review]
Thanks, perfect!

**Pull request merged**
